song/main/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index),
    url(r'^song/add/$', song_add, name="song_add"),
    url(r'^song/added/(?P<song_id>\d+)/$', song_added, name="song_added"),

    url(r'^store/(?P<store_id>\d+)/$', store_index, name="store_index"),
    
    url(r'^song/completed/(?P<store_id>\d+)/$', song_completed, name="song_completed"),

    url(r'^song/delete/(?P<song_id>\d+)/$', song_delete, name='song_delete'),
    url(r'^(?P<store_id>\d+)/song/all_delete/$', song_all_delete, name='song_all_delete'),
    url(r'^song/played/(?P<song_id>\d+)/$', song_played, name='song_played'),
    url(r'^song/return/(?P<song_id>\d+)/$', song_return, name='song_return'),
    
    url(r'^store/set/(?P<store_id>\d+)/$', store_set, name="store_set"),
]

song/song/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls', namespace="main"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

song/main/models.py
from django.db import models

class store(models.Model):
    TYPE1 = (
        ('1', 'melon'),
        ('2', 'genie'),
        ('3', 'bugs')
    )
    name = models.CharField(max_length=100)
    delay = models.IntegerField(default=0)
    site = models.CharField(max_length=1 ,choices=TYPE1)
    reset_list = models.IntegerField(default=0)
    reset_played = models.IntegerField(default=0)
    def __str__(self):
        return self.name

class song(models.Model):
    store = models.ForeignKey(store)
    order_time = models.DateTimeField(auto_now_add = True)
    title = models.CharField(max_length=50)
    singer = models.CharField(max_length=50)
    message = models.CharField(max_length=200, null=True)
    played = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    def __str__(self):
        return self.title

song/main/views.py
from django.shortcuts import render, redirect
from .models import *
from django.db import IntegrityError
import datetime

def index(request):
    return render(request, 'main/base.html')

def song_add(request):
    if request.method == 'GET':
        return render(request, 'main/song_add.html')
    else:
        title = request.POST.get('title')
        singer = request.POST.get('singer')
        message = request.POST.get('message')
        store_id = int(request.POST.get('store'))
        new_song = song.objects.create(title=title, singer=singer, message=message, store_id=store_id)
        return redirect("main:song_added", song_id=new_song.pk)

def song_added(request, song_id):
    context = {'song' : song.objects.get(pk=song_id)}
    return render(request, 'main/song_added.html', context)

def store_index(request, store_id):
    one_store = store.objects.get(pk=store_id)
    if one_store.reset_list != 0:
        time = datetime.datetime.now() - datetime.timedelta(hours=one_store.reset_list)
        song = one_store.song_set.filter(order_time__lte=time)
        song.filter(played=False).update(deleted=True)

    if one_store.reset_played != 0:
        time = datetime.datetime.now() - datetime.timedelta(hours=one_store.reset_played)
        song = one_store.song_set.filter(order_time__lte=time)
        song.filter(played=True).update(deleted=True)

    context = {'song' : one_store.song_set.filter(deleted=False).filter(played=False), 'store' : one_store }
    return render(request, 'main/store_index.html', context)

def song_completed(request, store_id):
    one_store = store.objects.get(pk=store_id)
    context = {'song' : one_store.song_set.filter(deleted=False).filter(played=True), 'store' : one_store }
    return render(request, 'main/song_completed.html', context)

def song_delete(request, song_id):
    context = song.objects.get(pk=song_id)
    context.delete()
    store_id = context.store.id
    return redirect('main:store_index', store_id=store_id)

def song_all_delete(request, store_id):
    store.objects.get(pk=store_id).song_set.all().delete()
    return redirect('main:store_index', store_id=store_id)

def song_played(request, song_id):
    song.objects.filter(pk=song_id).update(played=True)
    store_id = song.objects.get(pk=song_id).store.id
    return redirect('main:store_index', store_id)

def song_return(request, song_id):
    song.objects.filter(pk=song_id).update(played=False)
    store_id = song.objects.get(pk=song_id).store.id
    return redirect('main:song_completed', store_id)

def store_set(request, store_id):
    one_store = store.objects.get(pk=store_id)

    one_store.delay = int(request.POST.get('delay'))
    one_store.site = request.POST.get('site')
    one_store.reset_list = int(request.POST.get('reset_list'))
    one_store.reset_played = int(request.POST.get('reset_played'))

    one_store.save() 

    return redirect('main:store_index', store_id=store_id)

song/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>SPA</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <nav class="upper-nav">
    <div>
      <a href="#" class="nav-text">
        밤과 음악사이
      </a>
      <a href="#settings" class="setimg" id="set_btn">
        <img class="image" src = "{% static 'images/settings.png' %}" >                            
      </a>
    </div>
  </nav>

  <div class="app-root">
      {% block content %}
      {% endblock %}
  </div>

  <div class="modal-background hide">
      <button class="modal-close" id="close_modal"><img src="{% static 'images/close.png'%}"></button>
        
    <div class="modal">
        <div class="button-wrap">
        <div class="section-title">예상소요시간</div>
            <button class="est-time text-btn {% if store.delay == 30 %}selected{% endif %}" type="button" value="30" >30분</button>
            <button class="est-time text-btn {% if store.delay == 60 %}selected{% endif %}" type="button" value="60">60분</button>
        </div>
        <div class="button-wrap">
        <div class="section-title">검색 사이트</div>
            {% for a, b in store.TYPE1 %}
                <button type="button" class="searching-site img-btn {{ b }} {% if store.site == a %}selected{% endif %}" value="{{ a }}"></button>
            {% endfor %}
        </div>
        <div class="button-wrap">
            <div class="section-title">초기화 시간</div>
            <div class="subtitle">신청 플레이리스트</div>
            <button type="button" class="req-init-time text-btn {% if store.reset_list == 2 %}selected{% endif %}" value="2">2시간</button>
            <button type="button" class="req-init-time text-btn {% if store.reset_list == 4 %}selected{% endif %}" value="4">4시간</button>
            <button type="button" class="req-init-time text-btn {% if store.reset_list == 6 %}selected{% endif %}"  value="6">6시간</button>

            <div class="subtitle">완료 플레이리스트</div>
            <button type="button" class="finished-init-time text-btn {% if store.reset_played == 2 %}selected{% endif %}" value="2">2시간</button>
            <button type="button" class="finished-init-time text-btn {% if store.reset_played == 4 %}selected{% endif %}" value="4">4시간</button>
            <button type="button" class="finished-init-time text-btn {% if store.reset_played == 6 %}selected{% endif %}" value="6">6시간</button>
        </div>
        <button id = "fake_save" class="save" type="submit">저 &nbsp;장</button>

        <form id = "setting_form" style = "display:block" method="POST" action="{% url 'main:store_set' 1 %}">
            {% csrf_token %}  
            <input type="hidden" id="est_time" name="delay" value="{{ store.delay }}">
            <input type="hidden" id="searching_site" name="site" value="{{ store.site }}">
            <input type="hidden" id="req_init_time" name="reset_list" value="{{ store.reset_list }}">
            <input type="hidden" id="finished_init_time" name="reset_played" value="{{ store.reset_played }}">
            <button class="save" type="submit">저 &nbsp;장</button>
        </form>
    </div>
  </div>
</body>
<footer>
  {% block footer %}
  {% endblock %}
</footer>
</html>
<script
  src="https://code.jquery.com/jquery-3.3.1.slim.js"
  integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA="
  crossorigin="anonymous"></script>
<script>
  function setURL(url){
      location.href = url
  }

  let estTimeClass = document.getElementsByClassName("est-time");

  let estTimeBtn = function() {
      let attribute = this.getAttribute("value");
      document.getElementById('est_time').value = attribute;
  };

  for (let i = 0; i < estTimeClass.length; i++) {
      estTimeClass[i].addEventListener('click', estTimeBtn, false);
  }


  let searchingClass = document.getElementsByClassName("searching-site");

  let searchingBtn = function() {
      let attribute = this.getAttribute("value");
      document.getElementById('searching_site').value = attribute;
  };

  for (let i = 0; i < searchingClass.length; i++) {
      searchingClass[i].addEventListener('click', searchingBtn, false);
  }


  let reqClass = document.getElementsByClassName("req-init-time");

  let reqBtn = function() {
      let attribute = this.getAttribute("value");
      document.getElementById('req_init_time').value = attribute;
  };

  for (let i = 0; i < reqClass.length; i++) {
      reqClass[i].addEventListener('click', reqBtn, false);
  }

  let finishClass = document.getElementsByClassName("finished-init-time");

  let finishBtn = function() {
      let attribute = this.getAttribute("value");
      document.getElementById('finished_init_time').value = attribute;
  };

  for (let i = 0; i < finishClass.length; i++) {
      finishClass[i].addEventListener('click', finishBtn, false);
  }


  $('.est-time').click(function(){
      $('.est-time').removeClass('selected');
      $(this).addClass('selected');
  })

  $('.searching-site').click(function(){
      $('.searching-site').removeClass('selected');
      $(this).addClass('selected');
  })

  $('.req-init-time').click(function(){
      $('.req-init-time').removeClass('selected');
      $(this).addClass('selected');
  })

  $('.finished-init-time').click(function(){
      $('.finished-init-time').removeClass('selected');
      $(this).addClass('selected');
  })



  $('#set_btn').click(function(){
      $('.modal-background').removeClass('hide')
  })
  $('#close_modal').click(function(){
      $('.modal-background').addClass('hide')
  })

  $('#fake_save').click(function(){
      $("#setting_form").submit()
  });
  
</script>
  

song/main/templates/main/song_add.html
{% load static from staticfiles %}

<!DOCTYPE html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/myForm.css' %}">
    </head>
    <body>
        <div class="container">
            <a href="#">밤과 음악사이</a>
            <form method="POST" action="{% url 'main:song_add' %}">
                {% csrf_token %}
                <div class="input-element">
                    <div class="title left">가 수</div>
                    <input type="text" name="singer" id="artist"placeholder="가수명을 입력하세요.">
                </div>

                <div class="input-element">
                    <div class="title left">노래제목</div>
                    <input type="text" name="title" id="title" placeholder="노래제목을 입력하세요.">
                </div>
                
                <input type="hidden" value=1 name="store">
                <div class="row">
                    <input type="submit" value="완료">
                </div> 
            </form>
        </div>
    </body>
</html>

song/main/templates/main/song_added.html
{% load static from staticfiles %}

<!DOCTYPE html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/myForm.css' %}">
    </head>
    <body>
        <div class="container">
            <div class = "center">

                <div class = "song-info" >
                    {{song.singer}} - {{song.title}}
                </div>    
            
                <div class = "center-msg">
                    접수완료되었습니다. 
                </div>
            
                <div class = "bottom-msg">
                    예상 소요시간은 <b id="setTimevalue">{{song.store.delay}}</b>분 입니다.
                </div>
            </div>
        
            <div class="row">
                <form method="GET" action="{% url 'main:song_add' %}">
                    {% csrf_token %}
                    <input type="submit" value="확인">
                </form>
            </div> 
        </div>
    </body>
</html>

song/main/templates/main/song_completed.html
{% extends 'main/base.html' %}

{% block content %}
    <header>
        <nav class="lower-nav">
            <button type="button" onclick="location.href='{% url 'main:store_index' store_id=store.pk %}';">신청 플레이리스트</button>
            <button type="button" class="selected" onclick="setURL('#end')">완료 플레이리스트</button>
        </nav>
    </header>

    <div id="main">
        <article>
            {% for s in song %}
                <div class="song-element">
                    <div>{{s.singer}} - {{s.title}}</div>
                    <div>{{s.order_time|date:"Y .m .d"}}</div>
                    <div>
                        <a href="{% url 'main:song_return' song_id=s.pk %}">
                            <button type="button" class="refresh"></button>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </article>
    </div>

{% endblock %}

song/main/templates/main/song_complited.html
{% extends 'main/base.html' %}

{% block content %}
    <header>
        <nav class="lower-nav">
            <button type="button" onclick="{% url 'main:song_return' song_id=s.pk %}">신청 플레이리스트</button>
            <button type="button" class="selected" onclick="setURL('#end')">완료 플레이리스트</button>
            <div class="lower-nav-button-group">
                <button type="button" class="selected">시간순</button>
                <button type="button">날짜순</button>
                <button type="button">신청순</button>
            </div>
        </nav>
    </header>

    <div id="main">
        <article>
            {% for s in song %}
                <div class="song-element">
                    <div>{{s.singer}} - {{s.title}}</div>
                    <div>{{s.order_time|date:"Y .m .d"}}</div>
                    <div>
                        <a href="{% url 'main:song_return' song_id=s.pk %}">
                            <button type="button" class="refresh">
                                되돌리기
                            </button>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </article>
    </div>

{% endblock %}

{% block footer %}
    <a href="{% url 'main:song_all_delete' store_id=store.id %}">
        <button class ="init">초기화</button>
    </a>
{% endblock %}

song/main/templates/main/store_index.html
{% extends 'main/base.html' %}

{% block content %}
    <header>        
        <nav class="lower-nav">   
            <button type="button" class="selected">신청 플레이리스트</button>
            <button type="button" onclick="location.href='{% url 'main:song_completed' store_id=store.id %}';">완료 플레이리스트</button>
        </nav>
    
    </header>
    <div id="main">
        <article>
            {% ifequal song.count 0 %}
                신청된 노래가 없습니다.
            {% else %}       
                {% for s in song %}
                    <div class="song-element">
                        <div>{{s.singer}} - {{s.title}}</div>
                        <div>{{s.order_time|date:"Y .m .d"}}</div>
                        <div>  
                            {% if s.store.site == '1' %}
                                <a href="https://www.melon.com/search/total/index.htm?q={{s.singer}}+{{s.title}}&section=&searchGnbYn=Y&kkoSpl=Y&kkoDpType=&linkOrText=T&ipath=srch_form"
                                target="_blank" onclick = "location.href='{% url 'main:song_played' song_id=s.pk %}';">
                            {% elif s.store.site == '2' %}
                                <a href="http://www.genie.co.kr/search/searchMain?query={{s.singer}}%2520{{s.title}}"
                                target="_blank" onclick = "location.href='{% url 'main:song_played' song_id=s.pk %}';">
                            {% else %}
                                <a href="https://music.bugs.co.kr/search/integrated?q={{s.singer}}%20{{s.title}}"
                                target="_blank"  onclick = "location.href='{% url 'main:song_played' song_id=s.pk %}';">
                            {% endif %}
                            <button type="button"  class="search"></button>
                            </a>

                            <a href="{% url 'main:song_delete' song_id=s.pk %}">
                                <button type="button"  class="delete"></button>
                            </a>
                        </div>   
                    </div>
                {% endfor %}
            {% endifequal %}
                
        </article>
    </div>
{% endblock %}
{% block footer %}
    <a href="{% url 'main:song_all_delete' store_id=store.id %}">
        <button class ="init">
            초기화
        </button>
    </a>
{% endblock %}

song/main/templates/main/store_setting.html
<h4>설정</h4>
    <form method="POST" action="{% url 'main:store_set' store_id %}">
        {% csrf_token %}

        예상 소요시간
        <input type="radio" name="delay" value="30" checked /> 30
        <input type="radio" name="delay" value="60"/> 60
        <br>

        검색 사이트
        <input type="radio" name="site" value="1" checked /> 멜론
        <input type="radio" name="site" value="2"/> 지니
        <input type="radio" name="site" value="3"/> 벅스
        <br/>

        신청 플레이 리스트
        <input type="radio" name="reset_list" value="0" checked /> 설정 안함
        <input type="radio" name="reset_list" value="2"/> 2시간
        <input type="radio" name="reset_list" value="4"/> 4시간
        <input type="radio" name="reset_list" value="6"/> 6시간
        <br/>

        완료 플레이 리스트
        <input type="radio" name="played" value="0" checked/> 설정안함
        <input type="radio" name="played" value="2"/> 2시간
        <input type="radio" name="played" value="4"/> 4시간
        <input type="radio" name="played" value="6"/> 6시간
        <br/>
        <input type="submit" value="저장">
    </form>